version: "3.2"
services:
  sql-server:
    container_name: castiron-mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    # volumes:
    #   - mssqlsystem:/var/opt/mssql
    #   - mssqluser:/var/opt/sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "passwordABC123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
  postgresql:
    container_name: castiron-postgres
    image: postgres:12-alpine
    # volumes:
    #   - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"

# volumes:
#   mssqlsystem:
#   mssqluser:
#   postgresdata:
